---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
- name: burndown-git
outputs:
- name: build-output

run:
  path: burndown-git/ci/tasks/build.sh