resources:
  - name: burndown-git
    type: git
    source:
      uri: https://github.com/lukemueller/burndown.git
      branch: concourse

jobs:
  - name: test-and-build
    plan:
    - get: burndown-git
      trigger: true
    - task: test
      file: burndown-git/ci/tasks/test.yml
  - name: push-dev
    plan:
    - get: built-project/build/libs/burndown-1.0-SNAPSHOT.jar
      trigger: true
    - task: push-dev
      file: burndown-git/ci/tasks/push-dev.yml