resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/lukemueller/burndown.git
      branch: concourse

jobs:
  - name: build-and-test
    plan:
    - get: source-code
      trigger: true
    - task: test
      file: burndown/ci/tasks/test.yml